# Generated by Django 3.2.12 on 2023-10-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dn5paisaUserCredsMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=1000)),
                ('user_id', models.CharField(max_length=1000)),
                ('app_name', models.CharField(max_length=1000)),
                ('app_source', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('user_key', models.CharField(max_length=1000)),
                ('encryption_key', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('passwd', models.CharField(max_length=1000)),
                ('dob', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('is_main', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'dn_5paisa_creds_master',
            },
        ),
        migrations.CreateModel(
            name='DnAdminMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'dn_admin_master',
            },
        ),
        migrations.CreateModel(
            name='DnAngelUserCredsMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=1000)),
                ('user_id', models.CharField(max_length=1000)),
                ('api_key', models.CharField(max_length=1000)),
                ('totp_key', models.CharField(max_length=1000)),
                ('twoFA', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('is_main', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'dn_angel_user_creds_master',
            },
        ),
        migrations.CreateModel(
            name='DnBrokerMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dn_broker_master',
            },
        ),
        migrations.CreateModel(
            name='DnBrokerUserCredsMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=1000)),
                ('user_id', models.BigIntegerField()),
                ('broker_id', models.BigIntegerField()),
                ('broker_user_id', models.BigIntegerField()),
                ('broker_api_key', models.CharField(max_length=1000)),
                ('two_fa', models.CharField(max_length=1000)),
                ('broker_name', models.CharField(max_length=1000)),
                ('totp_encrypt_key', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField(default=0)),
                ('is_main', models.IntegerField(default=0)),
                ('do_twofa', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('is_background_task_running', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dn_broker_user_creds_master',
            },
        ),
        migrations.CreateModel(
            name='DnBrokerUserStatusMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('broker_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dn_broker_user_status_master',
            },
        ),
        migrations.CreateModel(
            name='DnFinvasiaUserCredsMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=1000)),
                ('user_id', models.CharField(max_length=1000)),
                ('totp_key', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('is_main', models.CharField(max_length=1000)),
                ('twoFA', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('vc', models.CharField(max_length=1000)),
                ('app_key', models.CharField(max_length=1000)),
                ('imei', models.CharField(max_length=1000)),
                ('access_token', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'dn_finvasia_user_creds_master',
            },
        ),
        migrations.CreateModel(
            name='DnFlattradeUserCredsMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=1000)),
                ('user_id', models.CharField(max_length=1000)),
                ('api_key', models.CharField(max_length=1000)),
                ('secret_key', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('totp_key', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('is_main', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'dn_flattrade_creds_master',
            },
        ),
        migrations.CreateModel(
            name='DnFyersUserCredsMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=1000)),
                ('fy_id', models.CharField(max_length=1000)),
                ('app_id', models.CharField(max_length=1000)),
                ('secret_key', models.CharField(max_length=1000)),
                ('pin', models.CharField(max_length=1000)),
                ('totp_key', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('is_main', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'dn_fyers_creds_master',
            },
        ),
        migrations.CreateModel(
            name='DnRomilBroker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=1000)),
                ('upper_level', models.CharField(max_length=1000)),
                ('upper_target', models.CharField(max_length=1000)),
                ('sl_upper', models.CharField(max_length=1000)),
                ('strike_ce', models.CharField(max_length=1000)),
                ('lower_level', models.CharField(max_length=1000)),
                ('lower_target', models.CharField(max_length=1000)),
                ('sl_lower', models.CharField(max_length=1000)),
                ('strike_pe', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('expiry', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('symbol', models.CharField(max_length=1000)),
                ('symbolNum', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'romil_broker',
            },
        ),
        migrations.CreateModel(
            name='DnUpstoxUserCredsMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=1000)),
                ('user_id', models.CharField(max_length=1000)),
                ('api_key', models.CharField(max_length=1000)),
                ('secret_key', models.CharField(max_length=1000)),
                ('pin', models.CharField(max_length=1000)),
                ('mobile_no', models.CharField(max_length=1000)),
                ('totp_key', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('is_main', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('access_token', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'dn_upstox_user_creds_master',
            },
        ),
        migrations.CreateModel(
            name='DnUseCaseMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('use_case', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dn_use_case_master',
            },
        ),
        migrations.CreateModel(
            name='DnUserMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=1000)),
                ('is_first', models.IntegerField(default=0)),
                ('timestamp', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dn_user_master',
            },
        ),
        migrations.CreateModel(
            name='DnUserRequestMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('otp', models.IntegerField()),
                ('is_approved', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dn_user_request_master',
            },
        ),
    ]
