# Generated by Django 3.2.12 on 2023-09-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DnAdminMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'dn_admin_master',
            },
        ),
        migrations.CreateModel(
            name='DnBrokerMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dn_broker_master',
            },
        ),
        migrations.CreateModel(
            name='DnBrokerUserCredsMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('broker_id', models.BigIntegerField()),
                ('broker_user_id', models.BigIntegerField()),
                ('broker_api_key', models.CharField(max_length=1000)),
                ('two_fa', models.CharField(max_length=1000)),
                ('totp_encrypt_key', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField(default=0)),
                ('is_main', models.IntegerField(default=0)),
                ('do_twofa', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dn_broker_user_creds_master',
            },
        ),
        migrations.CreateModel(
            name='DnBrokerUserStatusMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('broker_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dn_broker_user_status_master',
            },
        ),
        migrations.CreateModel(
            name='DnUseCaseMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('use_case', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dn_use_case_master',
            },
        ),
        migrations.CreateModel(
            name='DnUserMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=1000)),
                ('is_first', models.IntegerField(default=0)),
                ('timestamp', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dn_user_master',
            },
        ),
        migrations.CreateModel(
            name='DnUserRequestMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('is_approved', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dn_user_request_master',
            },
        ),
    ]
