# Generated by Django 3.2.12 on 2023-09-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnbrokerusercredsmaster',
            name='is_background_task_running',
            field=models.BooleanField(default=False),
        ),
    ]
