# Generated by Django 3.2.12 on 2023-09-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_dnbrokerusercredsmaster_is_background_task_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnuserrequestmaster',
            name='message',
        ),
        migrations.AddField(
            model_name='dnuserrequestmaster',
            name='otp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
