# Generated by Django 3.2.12 on 2023-10-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_dnfinvasiatradingview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnfinvasiatradingview',
            old_name='delivery',
            new_name='product_Type',
        ),
        migrations.AddField(
            model_name='dnfinvasiatradingview',
            name='strike_ce',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnfinvasiatradingview',
            name='strike_pe',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnfinvasiatradingview',
            name='strike_type',
            field=models.CharField(default='auto', max_length=1000),
            preserve_default=False,
        ),
    ]
