# Generated by Django 3.2.12 on 2023-10-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230916_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnFinvasiaUserCredsMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('broker_id', models.BigIntegerField()),
                ('broker_user_id', models.BigIntegerField()),
                ('broker_name', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField(default=0)),
                ('is_main', models.IntegerField(default=0)),
                ('do_twofa', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('vc', models.IntegerField(default=0)),
                ('app_key', models.IntegerField(default=0)),
                ('imei', models.IntegerField(default=0)),
                ('is_background_task_running', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dn_finvasia_user_creds_master',
            },
        ),
        migrations.AddField(
            model_name='dnbrokerusercredsmaster',
            name='app_key',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dnbrokerusercredsmaster',
            name='broker_name',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnbrokerusercredsmaster',
            name='imei',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dnbrokerusercredsmaster',
            name='vc',
            field=models.IntegerField(default=0),
        ),
    ]
