# Generated by Django 3.2.12 on 2023-10-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20231021_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnfinvasiatradingview',
            name='product_Type',
        ),
    ]
