# Generated by Django 3.2.12 on 2023-10-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_do_twofa_dnfinvasiausercredsmaster_twofa'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnfinvasiausercredsmaster',
            name='totp_encrypt_key',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
