# Generated by Django 3.2.12 on 2023-10-04 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_dnfinvasiausercredsmaster_totp_encrypt_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnbrokerusercredsmaster',
            name='app_key',
        ),
        migrations.RemoveField(
            model_name='dnbrokerusercredsmaster',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='dnbrokerusercredsmaster',
            name='vc',
        ),
    ]
