# Generated by Django 3.2.12 on 2023-10-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20231004_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnfinvasiausercredsmaster',
            name='app_key',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dnfinvasiausercredsmaster',
            name='imei',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dnfinvasiausercredsmaster',
            name='is_main',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dnfinvasiausercredsmaster',
            name='quantity',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dnfinvasiausercredsmaster',
            name='status',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dnfinvasiausercredsmaster',
            name='twoFA',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dnfinvasiausercredsmaster',
            name='user_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dnfinvasiausercredsmaster',
            name='vc',
            field=models.CharField(max_length=1000),
        ),
    ]
