# Generated by Django 3.2.12 on 2023-10-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_dntelegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='dntelegram',
            name='isAuthorized',
            field=models.BooleanField(default=False),
        ),
    ]
