# Generated by Django 3.2.12 on 2023-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20231004_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnfinvasiausercredsmaster',
            name='broker_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dnfinvasiausercredsmaster',
            name='broker_user_id',
            field=models.CharField(max_length=1000),
        ),
    ]
