# Generated by Django 3.2.12 on 2023-10-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20231004_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnfinvasiausercredsmaster',
            name='is_background_task_running',
            field=models.IntegerField(default=0),
        ),
    ]
