# Generated by Django 3.2.12 on 2023-10-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_dnfinvasiausercredsmaster_is_background_task_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnAngelUserCredsMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=1000)),
                ('broker_id', models.CharField(max_length=1000)),
                ('broker_user_id', models.CharField(max_length=1000)),
                ('broker_api_key', models.CharField(max_length=1000)),
                ('totp_encrypt_key', models.CharField(max_length=1000)),
                ('twoFA', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('is_main', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'dn_angel_user_creds_master',
            },
        ),
        migrations.CreateModel(
            name='DnUpstoxUserCredsMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=1000)),
                ('broker_id', models.CharField(max_length=1000)),
                ('broker_user_id', models.CharField(max_length=1000)),
                ('api_key', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('totp_key', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('is_main', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'dn_upstox_user_creds_master',
            },
        ),
    ]
