# Generated by Django 3.2.12 on 2023-10-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_dnsubscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnfinvasiausercredsmaster',
            old_name='totp_key',
            new_name='password',
        ),
    ]
