# Generated by Django 3.2.12 on 2023-10-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_totp_key_dnfinvasiausercredsmaster_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnangelusercredsmaster',
            old_name='twoFA',
            new_name='password',
        ),
    ]
