# Generated by Django 3.2.12 on 2023-10-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_dnangelusercredsmaster_dnupstoxusercredsmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dn5paisaUserCredsMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=1000)),
                ('user_id', models.CharField(max_length=1000)),
                ('app_name', models.CharField(max_length=1000)),
                ('app_source', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('user_key', models.CharField(max_length=1000)),
                ('encryption_key', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('passwd', models.CharField(max_length=1000)),
                ('dob', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('is_main', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'dn_5paisa_creds_master',
            },
        ),
        migrations.CreateModel(
            name='DnFlattradeUserCredsMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=1000)),
                ('user_id', models.CharField(max_length=1000)),
                ('api_key', models.CharField(max_length=1000)),
                ('secret_key', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('totp_key', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('is_main', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'dn_flattrade_creds_master',
            },
        ),
        migrations.CreateModel(
            name='DnFyersUserCredsMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=1000)),
                ('fy_id', models.CharField(max_length=1000)),
                ('app_id', models.CharField(max_length=1000)),
                ('secret_key', models.CharField(max_length=1000)),
                ('pin', models.CharField(max_length=1000)),
                ('totp_key', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('is_main', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'dn_fyers_creds_master',
            },
        ),
        migrations.CreateModel(
            name='DnRomilBroker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=1000)),
                ('upper_level', models.CharField(max_length=1000)),
                ('upper_target', models.CharField(max_length=1000)),
                ('sl_upper', models.CharField(max_length=1000)),
                ('strike_ce', models.CharField(max_length=1000)),
                ('lower_level', models.CharField(max_length=1000)),
                ('lower_target', models.CharField(max_length=1000)),
                ('sl_lower', models.CharField(max_length=1000)),
                ('strike_pe', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('expiry', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('symbol', models.CharField(max_length=1000)),
                ('symbolNum', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'romil_broker',
            },
        ),
        migrations.RenameField(
            model_name='dnangelusercredsmaster',
            old_name='broker_api_key',
            new_name='api_key',
        ),
        migrations.RenameField(
            model_name='dnangelusercredsmaster',
            old_name='broker_id',
            new_name='totp_key',
        ),
        migrations.RenameField(
            model_name='dnangelusercredsmaster',
            old_name='broker_user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='dnfinvasiausercredsmaster',
            old_name='broker_id',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='dnfinvasiausercredsmaster',
            old_name='broker_name',
            new_name='totp_key',
        ),
        migrations.RenameField(
            model_name='dnfinvasiausercredsmaster',
            old_name='broker_user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='dnupstoxusercredsmaster',
            old_name='broker_id',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='dnupstoxusercredsmaster',
            old_name='broker_user_id',
            new_name='mobile_no',
        ),
        migrations.RenameField(
            model_name='dnupstoxusercredsmaster',
            old_name='password',
            new_name='pin',
        ),
        migrations.RemoveField(
            model_name='dnangelusercredsmaster',
            name='totp_encrypt_key',
        ),
        migrations.RemoveField(
            model_name='dnfinvasiausercredsmaster',
            name='is_background_task_running',
        ),
        migrations.RemoveField(
            model_name='dnfinvasiausercredsmaster',
            name='totp_encrypt_key',
        ),
        migrations.AddField(
            model_name='dnbrokerusercredsmaster',
            name='user',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnupstoxusercredsmaster',
            name='secret_key',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnupstoxusercredsmaster',
            name='user',
            field=models.CharField(default='0', max_length=1000),
            preserve_default=False,
        ),
    ]
