# Generated by Django 3.2.12 on 2023-10-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_twofa_dnangelusercredsmaster_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnangelusercredsmaster',
            old_name='password',
            new_name='twoFA',
        ),
        migrations.RenameField(
            model_name='dnfinvasiausercredsmaster',
            old_name='password',
            new_name='totp_key',
        ),
    ]
