# Generated by Django 3.2.12 on 2023-10-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20231028_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnfinvasiausercredsmaster',
            old_name='totp_key',
            new_name='otpToken',
        ),
        migrations.RenameField(
            model_name='dnfinvasiausercredsmaster',
            old_name='twoFA',
            new_name='password',
        ),
    ]
