# Generated by Django 3.2.12 on 2023-10-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20231028_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnfinvasiausercredsmaster',
            old_name='otpToken',
            new_name='otpToken2',
        ),
        migrations.RenameField(
            model_name='dnfinvasiausercredsmaster',
            old_name='password',
            new_name='password2',
        ),
    ]
