# Generated by Django 3.2.12 on 2023-10-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20231028_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnfinvasiausercredsmaster',
            old_name='password2',
            new_name='otpToken',
        ),
    ]
