# Generated by Django 3.2.12 on 2023-10-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_password2_dnfinvasiausercredsmaster_otptoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnfinvasiausercredsmaster',
            old_name='otpToken2',
            new_name='password',
        ),
    ]
