# Generated by Django 3.2.12 on 2023-10-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_rename_otptoken2_dnfinvasiausercredsmaster_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnangelusercredsmaster',
            old_name='twoFA',
            new_name='otpToken',
        ),
        migrations.RenameField(
            model_name='dnangelusercredsmaster',
            old_name='totp_key',
            new_name='password',
        ),
    ]
