# Generated by Django 3.2.12 on 2023-11-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20231028_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnTelegramSubscribe',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('symbols', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'dn_telegram_subscribe',
            },
        ),
    ]
